/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jtpoint;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author absolute49
 */
public class EditVideo extends javax.swing.JFrame {

    /**
     * Creates new form EditVideo
     */
    private Video video;
    
    private String name;
    public EditVideo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namelabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        topiclabel = new javax.swing.JLabel();
        subjectlabel = new javax.swing.JLabel();
        taglabel = new javax.swing.JLabel();
        likeslabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setLocationByPlatform(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 0, 16), 3, true));
        jPanel1.setForeground(new java.awt.Color(165, 0, 16));

        namelabel.setFont(new java.awt.Font("Noto Sans", 3, 24)); // NOI18N
        namelabel.setForeground(new java.awt.Color(29, 165, 250));
        namelabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        namelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jtpoint/agent-bodyguard-policies-security-spy-user-icon--icon-search--22.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("URW Chancery L", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(200, 0, 16));
        jLabel4.setText("  Video Details :-");

        topiclabel.setBackground(new java.awt.Color(0, 0, 0));
        topiclabel.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        topiclabel.setForeground(new java.awt.Color(29, 165, 250));
        topiclabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        subjectlabel.setBackground(new java.awt.Color(0, 0, 0));
        subjectlabel.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        subjectlabel.setForeground(new java.awt.Color(29, 165, 250));
        subjectlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        taglabel.setBackground(new java.awt.Color(0, 0, 0));
        taglabel.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        taglabel.setForeground(new java.awt.Color(29, 165, 250));
        taglabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        likeslabel.setBackground(new java.awt.Color(0, 0, 0));
        likeslabel.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        likeslabel.setForeground(new java.awt.Color(29, 165, 250));
        likeslabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(29, 165, 250));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jtpoint/Subjects.png"))); // NOI18N
        jLabel10.setText("Subject :-");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(29, 165, 250));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jtpoint/managing-topic.png"))); // NOI18N
        jLabel11.setText("Topic :-");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(29, 165, 250));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jtpoint/green-price-tag-hi.png"))); // NOI18N
        jLabel12.setText("Tag :-");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(29, 165, 250));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jtpoint/thumb-up-icon.png"))); // NOI18N
        jLabel13.setText("Likes :-");

        jButton1.setBackground(new java.awt.Color(200, 0, 16));
        jButton1.setFont(new java.awt.Font("Noto Sans", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(29, 165, 200));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jtpoint/Delete_Icon.png"))); // NOI18N
        jButton1.setText("Delete Video");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 2, 3, new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("URW Chancery L", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(200, 0, 16));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jtpoint/0004530_400.png"))); // NOI18N
        jLabel1.setText("   Comments :-");

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 56, 56), 2, true));

        jList1.setBackground(new java.awt.Color(0, 0, 0));
        jList1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jList1.setFont(new java.awt.Font("URW Chancery L", 3, 24)); // NOI18N
        jList1.setForeground(new java.awt.Color(29, 165, 250));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton2.setBackground(new java.awt.Color(200, 0, 16));
        jButton2.setFont(new java.awt.Font("URW Chancery L", 3, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(29, 165, 250));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jtpoint/Delete_Icon.png"))); // NOI18N
        jButton2.setText("Delete Comment");
        jButton2.setToolTipText("");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 2, 3, new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(200, 0, 16));
        jButton3.setFont(new java.awt.Font("URW Chancery L", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(29, 165, 250));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jtpoint/0004530_400.png"))); // NOI18N
        jButton3.setText("Comment");
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 2, 3, new java.awt.Color(0, 0, 0)));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 0, 16), 2, true));

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(29, 165, 250));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 0, 16), 1, true));
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(topiclabel, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subjectlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(likeslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(namelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjectlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(topiclabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taglabel)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(likeslabel)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel11, topiclabel});

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            int k=jList1.getSelectedIndex();
            Comment ce=vec.elementAt(k);
            PreparedStatement st=c.prepareStatement("Delete from comments where commentid=?");
            st.setInt(1,ce.id);
            int s=st.executeUpdate();
            this.getcomment();
            
                    } catch (SQLException ex) {
            Logger.getLogger(EditVideo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        if(jList1.getSelectedIndex()==-1)
            jButton2.setEnabled(false);
        else
            jButton2.setEnabled(true);
        
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String text=this.jTextArea1.getText().toString();
        try {
            PreparedStatement st=c.prepareStatement("Insert into comments(videoid,userid,comment) Values(?,?,?)");
            st.setInt(1, video.videoid());
            st.setString(2, name);
            st.setString(3, text);
            int k=st.executeUpdate();
            Thread.currentThread().sleep(100);
            jTextArea1.setText("");
            this.getcomment();
        } catch (SQLException ex) {
            Logger.getLogger(EditVideo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(EditVideo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int id=video.videoid();
        try {
            PreparedStatement st=c.prepareStatement("Delete from Videos where videoid=?");
            st.setInt(1,video.videoid());
            int f=st.executeUpdate();
            PreparedStatement st2=c.prepareStatement("delete from comments where videoid=?");
            st2.setInt(1,video.videoid());
            f=st2.executeUpdate();
            this.dispose();
            JOptionPane.showMessageDialog(null, "Done", "Video Deleted please refresh page ", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (SQLException ex) {
            Logger.getLogger(EditVideo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        jButton3.setEnabled(true);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        jButton3.setEnabled(false);
    }//GEN-LAST:event_jButton3MouseExited

    /**
     * @param args the command line arguments
     */
    Connection c;
    Vector<Comment> vec;
    Vector<String> vec2;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditVideo().setVisible(true);
            }
        });
    }

    void call(Video v,String name) throws SQLException {
         //To change body of generated methods, choose Tools | Templates.
         this.video=v;
         this.name=name;
         this.setThings();
         
         
    }
    public void setThings() throws SQLException
    {
        namelabel.setText(name+"  ");
        subjectlabel.setText(video.subject());
        topiclabel.setText(video.topic());
        taglabel.setText(video.heading());
        likeslabel.setText(Integer.toString(video.likes()));
        jButton2.setEnabled(false);
        c=DriverManager.getConnection("jdbc:mysql://localhost:3306/users", "root", null);
        this.getcomment();
        
    }
    void getcomment()
    {
      vec=new Vector<Comment>();
      vec2=new Vector<String>();
        try {
            PreparedStatement st=c.prepareStatement("Select * from comments where videoid=? ");
            st.setInt(1, video.videoid());
            ResultSet rs=st.executeQuery();
            while(rs.next())
            {
                Comment c=new Comment(rs.getInt("commentid"),rs.getString("userid"),rs.getString("comment"));
                vec.add(c);
                vec2.add(c.toString());
            }
            jList1.setListData(vec2);
        } catch (SQLException ex) {
            Logger.getLogger(EditVideo.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel likeslabel;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel subjectlabel;
    private javax.swing.JLabel taglabel;
    private javax.swing.JLabel topiclabel;
    // End of variables declaration//GEN-END:variables
}
